import os
import sys
import random
from datetime import datetime, timezone, timedelta
from pathlib import Path
from pymongo import MongoClient

# Add src to path so we can import config
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from config import MONGO_URI, MONGO_DB, MONGO_COLL, ASSETS_COLL

def seed_reports():
    client = MongoClient(MONGO_URI)
    db = client[MONGO_DB]
    coll = db[MONGO_COLL]
    
    # Bangalore center
    center_lat = 12.9716
    center_lng = 77.5946
    
    # Generate 10 sample reports (potholes and trash) around Bangalore
    reports = []
    types = ["pothole", "trash"]
    statuses = ["pending", "acknowledged", "in_progress", "resolved"]
    
    for i in range(15):
        report_type = random.choice(types)
        status = random.choice(statuses)
        # Random offset around the center (roughly within the 5x5 grid generated by mock data)
        lat = center_lat + random.uniform(-0.04, 0.04)
        lng = center_lng + random.uniform(-0.04, 0.04)
        lat_s = round(lat, 5)
        lng_s = round(lng, 5)
        coord_key = f"{lng_s},{lat_s}"
        
        # Sample detection data
        severity = random.uniform(1.0, 5.0)
        detections = []
        num_dets = random.randint(1, 5)
        for _ in range(num_dets):
            detections.append({
                "class_name": report_type,
                "confidence": random.uniform(0.6, 0.99),
                "box": [
                    random.uniform(10, 100), random.uniform(10, 100),
                    random.uniform(150, 300), random.uniform(150, 300)
                ]
            })
            
        time_offset = timedelta(days=random.randint(0, 30), hours=random.randint(0, 24))
        report_time = datetime.now(timezone.utc) - time_offset
        
        # Base document
        doc = {
            "_id": f"{coord_key}:{report_type}",
            "email": f"sample_user_{i}@example.com",
            "location": {
                "type": "Point",
                "coordinates": [lng_s, lat_s]
            },
            "image": "https://placehold.co/600x400/png?text=Sample+" + report_type,
            "image_original": "https://placehold.co/600x400/png?text=Sample+" + report_type,
            "time": report_time,
            "type": report_type,
            "severity_score": severity,
            "detections": detections,
            "report_count": random.randint(1, 3),
            "created_at": report_time,
            "status": status,
            "status_updated_at": report_time if status != "pending" else None,
            "status_updated_by": "admin@netrai.local" if status != "pending" else None,
            "resolved": status == "resolved",
            "resolved_at": report_time if status == "resolved" else None,
            "resolved_by": "admin" if status == "resolved" else None,
        }
        
        if report_type == "trash":
            doc["environmental_impact"] = severity * 1.5
            doc["stats"] = {
                "total_detections": num_dets,
                "total_coverage_pct": random.uniform(5.0, 30.0),
                "category_counts": {
                    "plastic": random.randint(0, num_dets),
                    "organic": random.randint(0, num_dets)
                }
            }
            
        reports.append(doc)
        
    # Clear existing sample reports generated by this script or all?
    # Let's clear all reports to have a fresh state
    coll.delete_many({})
    coll.insert_many(reports)
    # Ensure geospatial index
    coll.create_index([("location", "2dsphere")])
    
    print(f"Inserted {len(reports)} sample reports into {MONGO_COLL} collection in Bangalore area.")

if __name__ == "__main__":
    seed_reports()
